on:
  pull_request:
    branches:
#      - main
      - master
  push:
    branches:
#      - main
      - master
      - develop

jobs:
  build-ios:
    name: 🎉 iOS Build
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64

      - name: Get Flutter dependencies
        run: flutter pub get

      - name: Install iOS dependencies
        run: pod install
        working-directory: ios

      - name: Build iOS app (unsigned)
        run: flutter build ios --release --no-codesign

      - name: Create Payload directory
        run: mkdir -p build/ios/iphoneos/Payload

      - name: Move Runner.app to Payload
        run: mv build/ios/iphoneos/Runner.app build/ios/iphoneos/Payload/

      - name: Zip output
        run: zip -qq -r -9 FlutterIpaExport.ipa Payload
        working-directory: build/ios/iphoneos

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          token: ${{ secrets.TEST }}  # Corrected input name
          file: build/ios/iphoneos/FlutterIpaExport.ipa
          tag: v1.0  # Ensure this tag exists in your repository
          overwrite: true
          body: "This is the first release"